version: '3'
services:
  db:
    image: mysql
    container_name: mysql-test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    platform: linux/x86_64